In [1]:
import pandas as pd     # 数据表
import jieba     # 中文分词

In [2]:
df_eng = pd.read_excel('text_analysis_twitter_sample.xlsx', index_col = 0)

In [3]:
df_eng.head()

,index,id,screen_name,time,link,text,source
0,49374,890587249372524544,auctnr1,2017-07-27T10:58:41-04:00,https://www.twitter.com/Reuters/statuses/89058...,"RT @Reuters MORE: Top U.S. general says, given...",Twitter for iPhone
1,83246,899354463055618048,SenatorTester,2017-08-20T15:36:27-04:00,https://www.twitter.com/SenatorTester/statuses...,T-minus 2 days until our first-ever Last Best ...,Twitter Web Client
2,100988,903272105738985472,KeithRothfus,2017-08-31T11:03:46-04:00,https://www.twitter.com/KeithRothfus/statuses/...,Please know that help is available. Visit http...,Twitter Web Client
3,193395,921001114409021440,HASCRepublicans,2017-10-19T09:12:31-04:00,https://www.twitter.com/HASCRepublicans/status...,Literally flying the wings off the A-10 in fig...,Twitter Web Client
4,12662,884911451449774080,SteveKnight25,2017-07-11T19:05:05-04:00,https://www.twitter.com/SteveKnight25/statuses...,Today the House unanimously passed my bill #HR...,Twitter Web Client

In [4]:
df_chn = pd.read_excel('text_analysis_ad.xlsx', index_col = 0)

In [5]:
df_chn.head()

,index,商品名称,商品类别,出版年,广告文本,广告标题
0,1596,五华牌香烟[May Blossom],烟草制品,1932,兰勃脱白脱勒公司 五华牌香烟 佛及尼埃香烟 二十枝装每包售国币大洋二角 五十枝装每罐售国币...,"五华牌香烟,""兰勃脱白脱勒公司 五华牌香烟 佛及尼埃香烟"""
1,5627,韦廉士红色清导丸[Dr.Willams' Pink Pills For Pale People],药品,1918,讲求卫生为人生本性天理固然也 人生首贵逐日大便通畅有序为天然所当如此也如若大便不利大肠阻塞则...,韦廉士红色清导丸:'讲求卫生为人生本性天理固然也'
2,13532,大炮台香烟[Three Castles Cigarettes],烟草制品,1935,"香味馥郁,不让名花 另有三炮台出售","大炮台香烟,""香味馥郁 不让名花"""
3,1133,婴孩自己药片[Baby's Own],药品,1930,差肩儿女 秀慧康强 闽有佳音讃羡婴孩自己药片 每年此际小儿患肠胃病者甚多而尤以南方各地天气翳...,"婴孩自己药片,""差肩儿女 秀慧康强 闽有佳音赞美婴孩自己药片"""
4,3146,亚士北罗药片[Aspro],药品,1933,何以亚士北罗是妇女们的腻友？各国妇女力证亚士北罗药片是她们最需要的药物！为什么？她们的经验知...,"亚士北罗药片,""妇女之腻友"""

## 情感词典

### NRC情感词典（NRC Emotion Lexicon）

In [6]:
nrc = pd.read_excel('NRC-Emotion-Lexicon.xlsx', usecols='A, F, AP:AY')
nrc = nrc.rename(columns={'English Word':'Engword', 'Chinese (simplified) Translation (Google Translate)':'Chnword'})
nrc.head()

D:\Software\Anaconda\Lib\site-packages\openpyxl\worksheet\_read_only.py:81: UserWarning: Unknown extension is not supported and will be removed
  for idx, row in parser.parse():

,Engword,Chnword,Positive,Negative,Anger,Anticipation,Disgust,Fear,Joy,Sadness,Surprise,Trust
0,aback,吓了一跳,0,0,0,0,0,0,0,0,0,0
1,abacus,算盘,0,0,0,0,0,0,0,0,0,1
2,abandon,放弃,0,1,0,0,0,1,0,1,0,0
3,abandoned,弃,0,1,1,0,0,1,0,1,0,0
4,abandonment,放弃,0,1,1,0,0,1,0,1,1,0

#### 英文语料

In [7]:
Positive, Negative, Anger, Anticipation, Disgust, Fear, Joy, Sadness, Surprise, Trust = [], [], [], [], [], [], [], [], [], []

for idx, row in nrc.iterrows():
    if row['Positive'] == 1:
        Positive.append(row['Engword'])
    if row['Negative'] == 1:
        Negative.append(row['Engword'])
    if row['Anger'] == 1:
        Anger.append(row['Engword'])
    if row['Anticipation'] == 1:
        Anticipation.append(row['Engword'])
    if row['Disgust'] == 1:
        Disgust.append(row['Engword'])
    if row['Fear'] == 1:
        Fear.append(row['Engword'])
    if row['Joy'] == 1:
        Joy.append(row['Engword'])
    if row['Sadness'] == 1:
        Sadness.append(row['Engword'])
    if row['Surprise'] == 1:
        Surprise.append(row['Engword'])
    if row['Trust'] == 1:
        Trust.append(row['Engword'])

In [8]:
emo_nrc_eng = pd.DataFrame(columns=['length_nrc', 'positive_nrc', 'negative_nrc',
                                    'anger_nrc', 'anticipation_nrc', 'disgust_nrc', 'fear_nrc',
                                    'joy_nrc', 'sadness_nrc', 'surprise_nrc', 'trust_nrc'])

for de in df_eng.index:
    positive, negative, anger, anticipation, disgust, fear, joy, sadness, surprise, trust = 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
    text = df_eng['text'][de].lower()
    wordlist = text.split()
    wordset = set(wordlist)
    wordfreq = []
    
    for word in wordset:
        freq = wordlist.count(word)
        if word in Positive:
            positive += freq
        if word in Negative:
            negative += freq
        if word in Anger:
            anger += freq
        if word in Anticipation:
            anticipation += freq
        if word in Disgust:
            disgust += freq
        if word in Fear:
            fear += freq
        if word in Joy:
            joy += freq
        if word in Sadness:
            sadness += freq
        if word in Surprise:
            surprise += freq
        if word in Trust:
            trust += freq
            
    emotion_info = {
        'length_nrc': len(wordlist),
        'positive_nrc': positive,
        'negative_nrc': negative,
        'anger_nrc': anger,
        'anticipation_nrc': anticipation,
        'disgust_nrc': disgust,
        'fear_nrc': fear,
        'joy_nrc': joy,
        'sadness_nrc': sadness,
        'surprise_nrc': surprise,
        'trust_nrc': trust
    }
    
    emo_info = pd.DataFrame([emotion_info])
    emo_nrc_eng = pd.concat([emo_nrc_eng, emo_info], ignore_index=True)
    
emo_nrc_eng.head()

,length_nrc,positive_nrc,negative_nrc,anger_nrc,anticipation_nrc,disgust_nrc,fear_nrc,joy_nrc,sadness_nrc,surprise_nrc,trust_nrc
0,22,2,0,0,1,0,0,0,0,0,2
1,18,1,0,0,1,0,0,1,0,1,1
2,16,1,0,0,0,0,0,0,0,0,0
3,22,1,1,1,0,0,2,0,0,0,0
4,20,0,1,1,0,1,1,0,1,1,1

In [9]:
df_eng = pd.concat([df_eng, emo_nrc_eng], axis=1)
df_eng.head()

,index,id,screen_name,time,link,text,source,length_nrc,positive_nrc,negative_nrc,anger_nrc,anticipation_nrc,disgust_nrc,fear_nrc,joy_nrc,sadness_nrc,surprise_nrc,trust_nrc
0,49374,890587249372524544,auctnr1,2017-07-27T10:58:41-04:00,https://www.twitter.com/Reuters/statuses/89058...,"RT @Reuters MORE: Top U.S. general says, given...",Twitter for iPhone,22,2,0,0,1,0,0,0,0,0,2
1,83246,899354463055618048,SenatorTester,2017-08-20T15:36:27-04:00,https://www.twitter.com/SenatorTester/statuses...,T-minus 2 days until our first-ever Last Best ...,Twitter Web Client,18,1,0,0,1,0,0,1,0,1,1
2,100988,903272105738985472,KeithRothfus,2017-08-31T11:03:46-04:00,https://www.twitter.com/KeithRothfus/statuses/...,Please know that help is available. Visit http...,Twitter Web Client,16,1,0,0,0,0,0,0,0,0,0
3,193395,921001114409021440,HASCRepublicans,2017-10-19T09:12:31-04:00,https://www.twitter.com/HASCRepublicans/status...,Literally flying the wings off the A-10 in fig...,Twitter Web Client,22,1,1,1,0,0,2,0,0,0,0
4,12662,884911451449774080,SteveKnight25,2017-07-11T19:05:05-04:00,https://www.twitter.com/SteveKnight25/statuses...,Today the House unanimously passed my bill #HR...,Twitter Web Client,20,0,1,1,0,1,1,0,1,1,1

#### 中文语料

In [10]:
Positive, Negative, Anger, Anticipation, Disgust, Fear, Joy, Sadness, Surprise, Trust = [], [], [], [], [], [], [], [], [], []

for idx, row in nrc.iterrows():
    if row['Positive'] == 1:
        Positive.append(row['Chnword'])
    if row['Negative'] == 1:
        Negative.append(row['Chnword'])
    if row['Anger'] == 1:
        Anger.append(row['Chnword'])
    if row['Anticipation'] == 1:
        Anticipation.append(row['Chnword'])
    if row['Disgust'] == 1:
        Disgust.append(row['Chnword'])
    if row['Fear'] == 1:
        Fear.append(row['Chnword'])
    if row['Joy'] == 1:
        Joy.append(row['Chnword'])
    if row['Sadness'] == 1:
        Sadness.append(row['Chnword'])
    if row['Surprise'] == 1:
        Surprise.append(row['Chnword'])
    if row['Trust'] == 1:
        Trust.append(row['Chnword'])

In [11]:
emo_nrc_chn = pd.DataFrame(columns=['length_nrc', 'positive_nrc', 'negative_nrc',
                                    'anger_nrc', 'anticipation_nrc', 'disgust_nrc', 'fear_nrc',
                                    'joy_nrc', 'sadness_nrc', 'surprise_nrc', 'trust_nrc'])

for dc in df_chn.index:
    positive, negative, anger, anticipation, disgust, fear, joy, sadness, surprise, trust = 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
    wordlist = list(jieba.cut(df_chn['广告文本'][dc]))
    wordset = set(wordlist)
    wordfreq = []
    
    for word in wordset:
        freq = wordlist.count(word)
        if word in Positive:
            positive += freq
        if word in Negative:
            negative += freq
        if word in Anger:
            anger += freq
        if word in Anticipation:
            anticipation += freq
        if word in Disgust:
            disgust += freq
        if word in Fear:
            fear += freq
        if word in Joy:
            joy += freq
        if word in Sadness:
            sadness += freq
        if word in Surprise:
            surprise += freq
        if word in Trust:
            trust += freq
            
    emotion_info = {
        'length_nrc': len(wordlist),
        'positive_nrc': positive,
        'negative_nrc': negative,
        'anger_nrc': anger,
        'anticipation_nrc': anticipation,
        'disgust_nrc': disgust,
        'fear_nrc': fear,
        'joy_nrc': joy,
        'sadness_nrc': sadness,
        'surprise_nrc': surprise,
        'trust_nrc': trust
    }
    
    emo_info = pd.DataFrame([emotion_info])
    emo_nrc_chn = pd.concat([emo_nrc_chn, emo_info], ignore_index=True)

emo_nrc_chn.head()

Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\Inanis\AppData\Local\Temp\jieba.cache
Loading model cost 1.337 seconds.
Prefix dict has been built successfully.

,length_nrc,positive_nrc,negative_nrc,anger_nrc,anticipation_nrc,disgust_nrc,fear_nrc,joy_nrc,sadness_nrc,surprise_nrc,trust_nrc
0,30,1,2,0,0,0,0,0,0,0,1
1,129,7,11,1,0,8,2,0,3,0,4
2,11,0,0,0,0,0,0,0,0,0,0
3,155,7,7,2,3,4,3,2,1,0,4
4,433,19,14,4,9,4,4,9,8,4,13

In [12]:
df_chn = pd.concat([df_chn, emo_nrc_chn], axis=1)
df_chn.head()

,index,商品名称,商品类别,出版年,广告文本,广告标题,length_nrc,positive_nrc,negative_nrc,anger_nrc,anticipation_nrc,disgust_nrc,fear_nrc,joy_nrc,sadness_nrc,surprise_nrc,trust_nrc
0,1596,五华牌香烟[May Blossom],烟草制品,1932,兰勃脱白脱勒公司 五华牌香烟 佛及尼埃香烟 二十枝装每包售国币大洋二角 五十枝装每罐售国币...,"五华牌香烟,""兰勃脱白脱勒公司 五华牌香烟 佛及尼埃香烟""",30,1,2,0,0,0,0,0,0,0,1
1,5627,韦廉士红色清导丸[Dr.Willams' Pink Pills For Pale People],药品,1918,讲求卫生为人生本性天理固然也 人生首贵逐日大便通畅有序为天然所当如此也如若大便不利大肠阻塞则...,韦廉士红色清导丸:'讲求卫生为人生本性天理固然也',129,7,11,1,0,8,2,0,3,0,4
2,13532,大炮台香烟[Three Castles Cigarettes],烟草制品,1935,"香味馥郁,不让名花 另有三炮台出售","大炮台香烟,""香味馥郁 不让名花""",11,0,0,0,0,0,0,0,0,0,0
3,1133,婴孩自己药片[Baby's Own],药品,1930,差肩儿女 秀慧康强 闽有佳音讃羡婴孩自己药片 每年此际小儿患肠胃病者甚多而尤以南方各地天气翳...,"婴孩自己药片,""差肩儿女 秀慧康强 闽有佳音赞美婴孩自己药片""",155,7,7,2,3,4,3,2,1,0,4
4,3146,亚士北罗药片[Aspro],药品,1933,何以亚士北罗是妇女们的腻友？各国妇女力证亚士北罗药片是她们最需要的药物！为什么？她们的经验知...,"亚士北罗药片,""妇女之腻友""",433,19,14,4,9,4,4,9,8,4,13

### 大连理工大学情感词典（DLUT Emotion Lexicon）

In [13]:
dlut = pd.read_excel('DLUT-Emotion-Lexicon.xlsx', usecols=['词语', '词性种类', '情感分类', '强度'])
dlut.head()

   词语  词性种类 情感分类  强度
0  脏乱   adj   NN   7
1  糟报   adj   NN   5
2  早衰   adj   NE   5
3  责备  verb   NN   5
4  贼眼  noun   NN   5

In [14]:
# 整理情感词典
Happy, Good, Surprise, Anger, Sad, Fear, Disgust  = [], [], [], [], [], [], []

for idx, row in dlut.iterrows():
    if row['情感分类'] in ['PA', 'PE']:
        Happy.append(row['词语'])
    if row['情感分类'] in ['PD', 'PH', 'PG', 'PB', 'PK']:
        Good.append(row['词语']) 
    if row['情感分类'] in ['PC']:
        Surprise.append(row['词语'])     
    if row['情感分类'] in ['NA']:
        Anger.append(row['词语'])    
    if row['情感分类'] in ['NB', 'NJ', 'NH', 'PF']:
        Sad.append(row['词语'])
    if row['情感分类'] in ['NI', 'NC', 'NG']:
        Fear.append(row['词语'])
    if row['情感分类'] in ['NE', 'ND', 'NN', 'NK', 'NL']:
        Disgust.append(row['词语'])
Positive = Happy + Good + Surprise
Negative = Anger + Sad + Fear + Disgust

In [15]:
emo_dlut = pd.DataFrame(columns=['length_dlut', 'positive_dlut', 'negative_dlut',
                                'anger_dlut', 'disgust_dlut', 'fear_dlut', 'good_dlut',
                                'sadness_dlut', 'surprise_dlut', 'happy_dlut'])

for dc in df_chn.index:
    positive, negative, anger, disgust, fear, sad, surprise, good, happy = 0, 0, 0, 0, 0, 0, 0, 0, 0
    wordlist = list(jieba.cut(df_chn['广告文本'][dc]))
    wordset = set(wordlist)
    wordfreq = []
    for word in wordset:
        freq = wordlist.count(word)
        if word in Positive:
            positive += freq
        if word in Negative:
            negative += freq
        if word in Anger:
            anger += freq
        if word in Disgust:
            disgust += freq
        if word in Fear:
            fear += freq
        if word in Sad:
            sad += freq
        if word in Surprise:
            surprise += freq
        if word in Good:
            good += freq
        if word in Happy:
            happy += freq
            
    emotion_info = {
        'length_dlut': len(wordlist),
        'positive_dlut': positive,
        'negative_dlut': negative,
        'anger_dlut': anger,
        'disgust_dlut': disgust,
        'fear_dlut': fear,
        'good_dlut': good,
        'sadness_dlut': sad,
        'surprise_dlut': surprise,
        'happy_dlut': happy
    }
    
    emo_info = pd.DataFrame([emotion_info])
    emo_dlut = pd.concat([emo_dlut, emo_info], ignore_index=True)
    
emo_dlut.head()

,length_dlut,positive_dlut,negative_dlut,anger_dlut,disgust_dlut,fear_dlut,good_dlut,sadness_dlut,surprise_dlut,happy_dlut
0,30,0,0,0,0,0,0,0,0,0
1,129,9,6,0,3,2,9,1,0,0
2,11,0,0,0,0,0,0,0,0,0
3,155,7,6,0,5,0,7,1,0,0
4,433,34,16,0,14,1,23,1,0,11

In [19]:
df_chn = pd.concat([df_chn, emo_dlut], axis=1)
df_chn.head()[:3]

,index,商品名称,商品类别,出版年,广告文本,广告标题,length_nrc,positive_nrc,negative_nrc,anger_nrc,...,length_dlut,positive_dlut,negative_dlut,anger_dlut,disgust_dlut,fear_dlut,good_dlut,sadness_dlut,surprise_dlut,happy_dlut
0,1596,五华牌香烟[May Blossom],烟草制品,1932,兰勃脱白脱勒公司 五华牌香烟 佛及尼埃香烟 二十枝装每包售国币大洋二角 五十枝装每罐售国币...,"五华牌香烟,""兰勃脱白脱勒公司 五华牌香烟 佛及尼埃香烟""",30,1,2,0,...,30,0,0,0,0,0,0,0,0,0
1,5627,韦廉士红色清导丸[Dr.Willams' Pink Pills For Pale People],药品,1918,讲求卫生为人生本性天理固然也 人生首贵逐日大便通畅有序为天然所当如此也如若大便不利大肠阻塞则...,韦廉士红色清导丸:'讲求卫生为人生本性天理固然也',129,7,11,1,...,129,9,6,0,3,2,9,1,0,0
2,13532,大炮台香烟[Three Castles Cigarettes],烟草制品,1935,"香味馥郁,不让名花 另有三炮台出售","大炮台香烟,""香味馥郁 不让名花""",11,0,0,0,...,11,0,0,0,0,0,0,0,0,0

In [17]:
df_chn.columns

Index(['index', '商品名称', '商品类别', '出版年', '广告文本', '广告标题', 'length_nrc',
       'positive_nrc', 'negative_nrc', 'anger_nrc', 'anticipation_nrc',
       'disgust_nrc', 'fear_nrc', 'joy_nrc', 'sadness_nrc', 'surprise_nrc',
       'trust_nrc', 'length_dlut', 'positive_dlut', 'negative_dlut',
       'anger_dlut', 'disgust_dlut', 'fear_dlut', 'good_dlut', 'sadness_dlut',
       'surprise_dlut', 'happy_dlut'],
      dtype='object')

------------------------

# 直播文本数据情感分析

In [6]:
import pandas as pd     # 数据表
import jieba     # 中文分词
import os

### 数据导入

In [7]:
# 指定文件夹路径
folder_path = '话术文本'

# 获取指定文件夹下所有的txt文件名
file_names = [f for f in os.listdir(folder_path) if f.endswith('.txt')]

# 初始化一个空的DataFrame来存储文件名和内容
df_chn = pd.DataFrame(columns=['文件名', '文件内容'])

# 循环读取每个txt文件，并将其添加到DataFrame中
for file_name in file_names:
    file_path = os.path.join(folder_path, file_name)
    with open(file_path, 'r', encoding='utf-8') as file:
        content = file.read()
        # 创建一个临时的DataFrame来存储当前文件的文件名和内容
        temp_df = pd.DataFrame({'文件名': [file_name], '文件内容': [content]})
        # 将临时DataFrame添加到主DataFrame中
        df_chn = pd.concat([df_chn, temp_df], ignore_index=True)

# 打印生成的DataFrame
print(df_chn)

               文件名                                               文件内容
0    九阳豆浆官方旗舰店.txt  原本的原汁原味，就它就是就跟那种鲜榨豆浆喝起来口感是一样的，它没有科技，没有狠活的，就喝起来...
1    五谷磨房官方旗舰店.txt  提前购就是咱囤货的时候，生产日期一个月左右，保质期是 12 个月，咱们相当于喝到明年的 4 ...
2      伊利官方旗舰店.txt  今天我三箱经典奶，老粉，你们给我做个证便不便宜？ 109 三箱经典纯牛奶上 5 号链接。\n...
3      天润官方旗舰店.txt  宝贝，放一百个心拍就行了，而且我们家的桶酸不单只是酸奶好吃，桶也很好用。像我们家装酸桶的话，...
4     娃哈哈官方旗舰店.txt  喜欢喝 AD 钙奶的直接去买 1 号链接，每一瓶 AD 钙奶里面都有 7% 为维A， 34%...
5        星巴克中国.txt  同步到自己的会员账户当中，诶，没错，对，然后像我们今天邀一天，我们把 19 种热门的咖啡全部...
6      汇源官方旗舰店.txt  现在此时此刻买回家，我家 1 号链接，我们上到百岁老人，下到 2 岁小孩，只要说你能够去接受...
7     王饱饱官方旗舰店.txt  这几位宝贝们，关于到身材上的是一定要买的是 3 + 6 号链接可以更快。可以的。为什么让你们...
8      西麦官方旗舰店.txt  买不到了。是的，姐姐们，就这 12 单，抓紧拍，一会真没了。我们是西麦官方前店官旗发货，正品...
9   认养一头牛官方旗舰店.txt  那为啥给牛的餐标这么好呢？就是因为他牛吃的好了，他心情好了，他产出来的奶的品质自然而然就会好...
10     轻上官方旗舰店.txt  我们里面没有加任何的蔗糖、白砂糖。没有。我们这个里面的喝起来是五分酸、五分甜，因为它不是说我...
11   麦纤之控官方旗舰店.txt  很均衡，去作为你的营养主食，早餐一日三餐都能去吃，在减脂期、运动期、身材管理期的宝宝再合适不...

### 导入NRC词典

In [8]:
nrc = pd.read_excel('NRC-Emotion-Lexicon.xlsx', usecols='A, F, AP:AY')
nrc = nrc.rename(columns={'English Word':'Engword', 'Chinese (simplified) Translation (Google Translate)':'Chnword'})
nrc.head()

D:\Software\Anaconda\Lib\site-packages\openpyxl\worksheet\_read_only.py:81: UserWarning: Unknown extension is not supported and will be removed
  for idx, row in parser.parse():

,Engword,Chnword,Positive,Negative,Anger,Anticipation,Disgust,Fear,Joy,Sadness,Surprise,Trust
0,aback,吓了一跳,0,0,0,0,0,0,0,0,0,0
1,abacus,算盘,0,0,0,0,0,0,0,0,0,1
2,abandon,放弃,0,1,0,0,0,1,0,1,0,0
3,abandoned,弃,0,1,1,0,0,1,0,1,0,0
4,abandonment,放弃,0,1,1,0,0,1,0,1,1,0

In [9]:
Positive, Negative, Anger, Anticipation, Disgust, Fear, Joy, Sadness, Surprise, Trust = [], [], [], [], [], [], [], [], [], []

for idx, row in nrc.iterrows():
    if row['Positive'] == 1:
        Positive.append(row['Chnword'])
    if row['Negative'] == 1:
        Negative.append(row['Chnword'])
    if row['Anger'] == 1:
        Anger.append(row['Chnword'])
    if row['Anticipation'] == 1:
        Anticipation.append(row['Chnword'])
    if row['Disgust'] == 1:
        Disgust.append(row['Chnword'])
    if row['Fear'] == 1:
        Fear.append(row['Chnword'])
    if row['Joy'] == 1:
        Joy.append(row['Chnword'])
    if row['Sadness'] == 1:
        Sadness.append(row['Chnword'])
    if row['Surprise'] == 1:
        Surprise.append(row['Chnword'])
    if row['Trust'] == 1:
        Trust.append(row['Chnword'])

In [10]:
emo_nrc_chn = pd.DataFrame(columns=['length_nrc', 'positive_nrc', 'negative_nrc',
                                    'anger_nrc', 'anticipation_nrc', 'disgust_nrc', 'fear_nrc',
                                    'joy_nrc', 'sadness_nrc', 'surprise_nrc', 'trust_nrc'])

for dc in df_chn.index:
    positive, negative, anger, anticipation, disgust, fear, joy, sadness, surprise, trust = 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
    wordlist = list(jieba.cut(df_chn['文件内容'][dc]))
    wordset = set(wordlist)
    wordfreq = []
    
    for word in wordset:
        freq = wordlist.count(word)
        if word in Positive:
            positive += freq
        if word in Negative:
            negative += freq
        if word in Anger:
            anger += freq
        if word in Anticipation:
            anticipation += freq
        if word in Disgust:
            disgust += freq
        if word in Fear:
            fear += freq
        if word in Joy:
            joy += freq
        if word in Sadness:
            sadness += freq
        if word in Surprise:
            surprise += freq
        if word in Trust:
            trust += freq
            
    emotion_info = {
        'length_nrc': len(wordlist),
        'positive_nrc': positive,
        'negative_nrc': negative,
        'anger_nrc': anger,
        'anticipation_nrc': anticipation,
        'disgust_nrc': disgust,
        'fear_nrc': fear,
        'joy_nrc': joy,
        'sadness_nrc': sadness,
        'surprise_nrc': surprise,
        'trust_nrc': trust
    }
    
    emo_info = pd.DataFrame([emotion_info])
    emo_nrc_chn = pd.concat([emo_nrc_chn, emo_info], ignore_index=True)

emo_nrc_chn.head()

Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\Inanis\AppData\Local\Temp\jieba.cache
Loading model cost 1.331 seconds.
Prefix dict has been built successfully.

,length_nrc,positive_nrc,negative_nrc,anger_nrc,anticipation_nrc,disgust_nrc,fear_nrc,joy_nrc,sadness_nrc,surprise_nrc,trust_nrc
0,9537,373,269,122,109,62,145,75,146,80,173
1,7012,518,161,41,103,74,69,68,118,41,170
2,6556,360,111,41,32,32,42,27,65,10,54
3,7322,373,120,34,80,53,41,88,30,46,170
4,7633,276,135,30,77,39,24,81,50,38,121

### 大连理工大学情感词典（DLUT Emotion Lexicon）

In [11]:
dlut = pd.read_excel('DLUT-Emotion-Lexicon.xlsx', usecols=['词语', '词性种类', '情感分类', '强度'])
dlut.head()

   词语  词性种类 情感分类  强度
0  脏乱   adj   NN   7
1  糟报   adj   NN   5
2  早衰   adj   NE   5
3  责备  verb   NN   5
4  贼眼  noun   NN   5

In [12]:
# 整理情感词典
Happy, Good, Surprise, Anger, Sad, Fear, Disgust  = [], [], [], [], [], [], []

for idx, row in dlut.iterrows():
    if row['情感分类'] in ['PA', 'PE']:
        Happy.append(row['词语'])
    if row['情感分类'] in ['PD', 'PH', 'PG', 'PB', 'PK']:
        Good.append(row['词语']) 
    if row['情感分类'] in ['PC']:
        Surprise.append(row['词语'])     
    if row['情感分类'] in ['NA']:
        Anger.append(row['词语'])    
    if row['情感分类'] in ['NB', 'NJ', 'NH', 'PF']:
        Sad.append(row['词语'])
    if row['情感分类'] in ['NI', 'NC', 'NG']:
        Fear.append(row['词语'])
    if row['情感分类'] in ['NE', 'ND', 'NN', 'NK', 'NL']:
        Disgust.append(row['词语'])
Positive = Happy + Good + Surprise
Negative = Anger + Sad + Fear + Disgust

In [13]:
emo_dlut = pd.DataFrame(columns=['length_dlut', 'positive_dlut', 'negative_dlut',
                                'anger_dlut', 'disgust_dlut', 'fear_dlut', 'good_dlut',
                                'sadness_dlut', 'surprise_dlut', 'happy_dlut'])

for dc in df_chn.index:
    positive, negative, anger, disgust, fear, sad, surprise, good, happy = 0, 0, 0, 0, 0, 0, 0, 0, 0
    wordlist = list(jieba.cut(df_chn['文件内容'][dc]))
    wordset = set(wordlist)
    wordfreq = []
    for word in wordset:
        freq = wordlist.count(word)
        if word in Positive:
            positive += freq
        if word in Negative:
            negative += freq
        if word in Anger:
            anger += freq
        if word in Disgust:
            disgust += freq
        if word in Fear:
            fear += freq
        if word in Sad:
            sad += freq
        if word in Surprise:
            surprise += freq
        if word in Good:
            good += freq
        if word in Happy:
            happy += freq
            
    emotion_info = {
        'length_dlut': len(wordlist),
        'positive_dlut': positive,
        'negative_dlut': negative,
        'anger_dlut': anger,
        'disgust_dlut': disgust,
        'fear_dlut': fear,
        'good_dlut': good,
        'sadness_dlut': sad,
        'surprise_dlut': surprise,
        'happy_dlut': happy
    }
    
    emo_info = pd.DataFrame([emotion_info])
    emo_dlut = pd.concat([emo_dlut, emo_info], ignore_index=True)
    
emo_dlut.head()

,length_dlut,positive_dlut,negative_dlut,anger_dlut,disgust_dlut,fear_dlut,good_dlut,sadness_dlut,surprise_dlut,happy_dlut
0,9537,170,74,0,68,6,129,0,0,41
1,7012,269,33,0,24,7,228,2,0,41
2,6556,235,39,0,32,7,197,0,1,37
3,7322,403,32,0,28,3,328,1,0,75
4,7633,194,23,0,18,2,164,3,0,30

In [14]:
df_chn = pd.concat([df_chn, emo_dlut], axis=1)
df_chn.head()[:3]

,文件名,文件内容,length_dlut,positive_dlut,negative_dlut,anger_dlut,disgust_dlut,fear_dlut,good_dlut,sadness_dlut,surprise_dlut,happy_dlut
0,九阳豆浆官方旗舰店.txt,原本的原汁原味，就它就是就跟那种鲜榨豆浆喝起来口感是一样的，它没有科技，没有狠活的，就喝起来...,9537,170,74,0,68,6,129,0,0,41
1,五谷磨房官方旗舰店.txt,提前购就是咱囤货的时候，生产日期一个月左右，保质期是 12 个月，咱们相当于喝到明年的 4 ...,7012,269,33,0,24,7,228,2,0,41
2,伊利官方旗舰店.txt,今天我三箱经典奶，老粉，你们给我做个证便不便宜？ 109 三箱经典纯牛奶上 5 号链接。\n...,6556,235,39,0,32,7,197,0,1,37

In [15]:
# 将 df_chn 数据表保存为 XLSX 格式的文件
output_file = '情感词典分析.xlsx'
df_chn.to_excel(output_file, index=False)

print(f'DataFrame has been saved to {output_file}')

DataFrame has been saved to 情感词典分析.xlsx